### PR TITLE
Dependencies updated

### PR DESCRIPTION
**Pull request by jesusprubio**
Hi again, I need this to be compatible with my project. Everything seems to keep working fine, could you push it to Bower registry please? :)

Thanks

### CODE REVIEW

**Comment by adracus** [comment]
I'll include and add it tomorrow (I hope). Until then have a Happy New Year :)

**Comment by adracus** [comment]
I downloaded your commit, but it seems that the alignment of text is incorrect as well as the type=password flag. Is the same happening for your local preview?

**Comment by jesusprubio** [comment]
Hi again, Happy New Year! :)
I've made another clean PR for to avoid these problems.
https://github.com/Adracus/login-box/pull/4

**Comment by jesusprubio** [comment]
Hi again :), this is not happening to me? In fact I tested the code in Sublime and Brackets looking for something strange.

**Comment by adracus** [comment]
Sorry for the really late reply. The password entry is not replaced with dots. This is why I'll close this.

**Pull request closed without merging**
